
name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/continuous-integration.yml@1.4.1"
    with:
      php-versions: '["7.2", "7.3", "7.4", "8.0"]'
